version: "3.8"
services:
    web:
        image: georgilesov/bgapp-web
        deploy:
            replicas: 2
        ports:
            - 8080:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
        networks:
            - app-network
        depends_on:
            - db

    php-fpm:
       image georgilesov/bgapp-php-fpm
       volumes:
            - ./web:/var/www/html
       networks:
           - app-network

    db:
        image: georgilesov/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
